/**
 * Simple Inventory API
 * This is a simple API for a DataScan test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: goldensoftworks@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package gio.quiroga.datascantest1.services.data_models

import java.time.LocalDateTime


/**
 * 
 * @param numTRX 
 * @param cliente 
 * @param fecha 
 */
data class Factura (
    val numTRX: Int? = null,
    val cliente: String? = null,
    val fecha: String? = null
) {
}